---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: myntra
spec:
  replicas: 3
  selector:
    matchLabels:
      app: myntra
  template:
    metadata:
      labels:
        app: myntra
    spec:
      containers:
      - name: myntra
        image: roopak1991/myntra:v1
        ports:
        - containerPort: 3000

---
apiVersion: v1
kind: Service
metadata:
  name: muntra-service
spec:
  selector:
    app: myntra
  ports:
  - protocol: TCP 
    port: 80 
    targetPort: 3000
  type: LoadBalancer
